// import { IWebpackStatsV3 } from "./webpack.3.model";
import { IWebpackStatsV5 } from "./webpack.5.model"

/** for compatibility check and unit testing */
export const WEBPACK_5_STUB: IWebpackStatsV5 = {
	hash: "f26eabad661888458e1f",
	version: "5.74.0",
	time: 2266,
	builtAt: 1663594882546,
	publicPath: "auto",
	outputPath: "/mnt/disk273/doc/coding/webpack-dep-graph/dist",
	assetsByChunkName: { main: ["bundle.js"] },
	assets: [
		{
			type: "asset",
			name: "bundle.js",
			size: 541985,
			emitted: true,
			comparedForEmit: false,
			cached: false,
			info: { javascriptModule: false, size: 541985 },
			chunkNames: ["main"],
			chunkIdHints: [],
			auxiliaryChunkNames: [],
			auxiliaryChunkIdHints: [],
			related: {},
			chunks: ["main"],
			auxiliaryChunks: [],
			isOverSizeLimit: false,
		},
	],
	chunks: [
		{
			rendered: true,
			initial: true,
			entry: true,
			recorded: false,
			size: 460261,
			sizes: { javascript: 459370, runtime: 891 },
			names: ["main"],
			idHints: [],
			runtime: ["main"],
			files: ["bundle.js"],
			auxiliaryFiles: [],
			hash: "d27c600eb7caf2a4d6ea",
			childrenByOrder: {},
			id: "main",
			siblings: [],
			parents: [],
			children: [],
			modules: [
				{
					type: "module",
					moduleType: "javascript/auto",
					layer: null,
					size: 3837,
					sizes: { javascript: 3837 },
					built: true,
					codeGenerated: true,
					buildTimeExecuted: false,
					cached: false,
					identifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/deps.config.ts",
					name: "./deps.config.ts",
					nameForCondition:
						"/mnt/disk273/doc/coding/webpack-dep-graph/deps.config.ts",
					index: 2,
					preOrderIndex: 2,
					index2: 0,
					postOrderIndex: 0,
					cacheable: true,
					optional: false,
					orphan: false,
					dependent: true,
					issuer: "/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
					issuerName: "./src/index.ts",
					issuerPath: [
						{
							identifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
							name: "./src/index.ts",
							profile: {
								total: 0,
								resolving: 0,
								restoring: 0,
								building: 0,
								integration: 0,
								storing: 0,
								additionalResolving: 0,
								additionalIntegration: 0,
								factory: 0,
								dependencies: 0,
							},
							id: "./src/index.ts",
						},
					],
					failed: false,
					errors: 0,
					warnings: 0,
					profile: {
						total: 26,
						resolving: 5,
						restoring: 0,
						building: 21,
						integration: 0,
						storing: 0,
						additionalResolving: 1,
						additionalIntegration: 0,
						factory: 5,
						dependencies: 1,
					},
					id: "./deps.config.ts",
					issuerId: "./src/index.ts",
					chunks: ["main"],
					assets: [],
					reasons: [
						{
							moduleIdentifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
							module: "./src/index.ts",
							moduleName: "./src/index.ts",
							resolvedModuleIdentifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
							resolvedModule: "./src/index.ts",
							type: "cjs require",
							active: true,
							explanation: "",
							userRequest: "../deps.config",
							loc: "35:20-45",
							moduleId: "./src/index.ts",
							resolvedModuleId: "./src/index.ts",
						},
						{
							moduleIdentifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/utils/graphml.ts",
							module: "./src/utils/graphml.ts",
							moduleName: "./src/utils/graphml.ts",
							resolvedModuleIdentifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/utils/graphml.ts",
							resolvedModule: "./src/utils/graphml.ts",
							type: "cjs require",
							active: true,
							explanation: "",
							userRequest: "../../deps.config",
							loc: "55:20-48",
							moduleId: "./src/utils/graphml.ts",
							resolvedModuleId: "./src/utils/graphml.ts",
						},
						{
							moduleIdentifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/webpack-stats/dependenciesUUIDMap.ts",
							module: "./src/webpack-stats/dependenciesUUIDMap.ts",
							moduleName:
								"./src/webpack-stats/dependenciesUUIDMap.ts",
							resolvedModuleIdentifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/webpack-stats/dependenciesUUIDMap.ts",
							resolvedModule:
								"./src/webpack-stats/dependenciesUUIDMap.ts",
							type: "cjs require",
							active: true,
							explanation: "",
							userRequest: "../../deps.config",
							loc: "40:20-48",
							moduleId:
								"./src/webpack-stats/dependenciesUUIDMap.ts",
							resolvedModuleId:
								"./src/webpack-stats/dependenciesUUIDMap.ts",
						},
						{
							moduleIdentifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/webpack-stats/webpackStats.ts",
							module: "./src/webpack-stats/webpackStats.ts",
							moduleName: "./src/webpack-stats/webpackStats.ts",
							resolvedModuleIdentifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/webpack-stats/webpackStats.ts",
							resolvedModule:
								"./src/webpack-stats/webpackStats.ts",
							type: "cjs require",
							active: true,
							explanation: "",
							userRequest: "../../deps.config",
							loc: "4:20-48",
							moduleId: "./src/webpack-stats/webpackStats.ts",
							resolvedModuleId:
								"./src/webpack-stats/webpackStats.ts",
						},
					],
					usedExports: null,
					providedExports: ["__esModule", "depsConfig"],
					optimizationBailout: [],
					depth: 1,
				},
				{
					type: "module",
					moduleType: "javascript/dynamic",
					layer: null,
					size: 519,
					sizes: { javascript: 519 },
					built: true,
					codeGenerated: true,
					buildTimeExecuted: false,
					cached: false,
					identifier:
						"javascript/dynamic|/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/available-typed-arrays/index.js",
					name: "./node_modules/available-typed-arrays/index.js",
					nameForCondition:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/available-typed-arrays/index.js",
					index: 55,
					preOrderIndex: 55,
					index2: 46,
					postOrderIndex: 46,
					cacheable: true,
					optional: false,
					orphan: false,
					dependent: true,
					issuer: "/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/which-typed-array/index.js",
					issuerName: "./node_modules/which-typed-array/index.js",
					issuerPath: [
						{
							identifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
							name: "./src/index.ts",
							profile: {
								total: 0,
								resolving: 0,
								restoring: 0,
								building: 0,
								integration: 0,
								storing: 0,
								additionalResolving: 0,
								additionalIntegration: 0,
								factory: 0,
								dependencies: 0,
							},
							id: "./src/index.ts",
						},
						{
							identifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/utils/graphviz.ts",
							name: "./src/utils/graphviz.ts",
							profile: {
								total: 0,
								resolving: 0,
								restoring: 0,
								building: 0,
								integration: 0,
								storing: 0,
								additionalResolving: 0,
								additionalIntegration: 0,
								factory: 0,
								dependencies: 0,
							},
							id: "./src/utils/graphviz.ts",
						},
						{
							identifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/graphviz/lib/graphviz.js",
							name: "./node_modules/graphviz/lib/graphviz.js",
							profile: {
								total: 130,
								resolving: 124,
								restoring: 0,
								building: 6,
								integration: 0,
								storing: 0,
								additionalResolving: 0,
								additionalIntegration: 0,
								factory: 124,
								dependencies: 0,
							},
							id: "./node_modules/graphviz/lib/graphviz.js",
						},
						{
							identifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/graphviz/lib/deps/graph.js",
							name: "./node_modules/graphviz/lib/deps/graph.js",
							profile: {
								total: 42,
								resolving: 32,
								restoring: 0,
								building: 10,
								integration: 0,
								storing: 0,
								additionalResolving: 0,
								additionalIntegration: 0,
								factory: 32,
								dependencies: 0,
							},
							id: "./node_modules/graphviz/lib/deps/graph.js",
						},
						{
							identifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/util/util.js",
							name: "./node_modules/util/util.js",
							profile: {
								total: 0,
								resolving: 0,
								restoring: 0,
								building: 0,
								integration: 0,
								storing: 0,
								additionalResolving: 0,
								additionalIntegration: 0,
								factory: 0,
								dependencies: 0,
							},
							id: "./node_modules/util/util.js",
						},
						{
							identifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/util/support/types.js",
							name: "./node_modules/util/support/types.js",
							profile: {
								total: 0,
								resolving: 0,
								restoring: 0,
								building: 0,
								integration: 0,
								storing: 0,
								additionalResolving: 0,
								additionalIntegration: 0,
								factory: 0,
								dependencies: 0,
							},
							id: "./node_modules/util/support/types.js",
						},
						{
							identifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/which-typed-array/index.js",
							name: "./node_modules/which-typed-array/index.js",
							profile: {
								total: 0,
								resolving: 0,
								restoring: 0,
								building: 0,
								integration: 0,
								storing: 0,
								additionalResolving: 0,
								additionalIntegration: 0,
								factory: 0,
								dependencies: 0,
							},
							id: "./node_modules/which-typed-array/index.js",
						},
					],
					failed: false,
					errors: 0,
					warnings: 0,
					profile: {
						total: 0,
						resolving: 0,
						restoring: 0,
						building: 0,
						integration: 0,
						storing: 0,
						additionalResolving: 0,
						additionalIntegration: 0,
						factory: 0,
						dependencies: 0,
					},
					id: "./node_modules/available-typed-arrays/index.js",
					issuerId: "./node_modules/which-typed-array/index.js",
					chunks: ["main"],
					assets: [],
					reasons: [
						{
							moduleIdentifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/is-typed-array/index.js",
							module: "./node_modules/is-typed-array/index.js",
							moduleName:
								"./node_modules/is-typed-array/index.js",
							resolvedModuleIdentifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/is-typed-array/index.js",
							resolvedModule:
								"./node_modules/is-typed-array/index.js",
							type: "cjs require",
							active: true,
							explanation: "",
							userRequest: "available-typed-arrays",
							loc: "4:27-60",
							moduleId: "./node_modules/is-typed-array/index.js",
							resolvedModuleId:
								"./node_modules/is-typed-array/index.js",
						},
						{
							moduleIdentifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/which-typed-array/index.js",
							module: "./node_modules/which-typed-array/index.js",
							moduleName:
								"./node_modules/which-typed-array/index.js",
							resolvedModuleIdentifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/which-typed-array/index.js",
							resolvedModule:
								"./node_modules/which-typed-array/index.js",
							type: "cjs require",
							active: true,
							explanation: "",
							userRequest: "available-typed-arrays",
							loc: "4:27-60",
							moduleId:
								"./node_modules/which-typed-array/index.js",
							resolvedModuleId:
								"./node_modules/which-typed-array/index.js",
						},
						{
							moduleIdentifier:
								"javascript/dynamic|/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/available-typed-arrays/index.js",
							module: "./node_modules/available-typed-arrays/index.js",
							moduleName:
								"./node_modules/available-typed-arrays/index.js",
							resolvedModuleIdentifier:
								"javascript/dynamic|/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/available-typed-arrays/index.js",
							resolvedModule:
								"./node_modules/available-typed-arrays/index.js",
							type: "cjs self exports reference",
							active: true,
							explanation: "",
							userRequest: null,
							loc: "19:0-14",
							moduleId:
								"./node_modules/available-typed-arrays/index.js",
							resolvedModuleId:
								"./node_modules/available-typed-arrays/index.js",
						},
					],
					usedExports: null,
					providedExports: null,
					optimizationBailout: [
						"CommonJS bailout: module.exports is used directly at 19:0-14",
					],
					depth: 7,
				},
				{
					type: "module",
					moduleType: "javascript/auto",
					layer: null,
					size: 3932,
					sizes: { javascript: 3932 },
					built: true,
					codeGenerated: true,
					buildTimeExecuted: false,
					cached: false,
					identifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/base64-js/index.js",
					name: "./node_modules/base64-js/index.js",
					nameForCondition:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/base64-js/index.js",
					index: 63,
					preOrderIndex: 63,
					index2: 58,
					postOrderIndex: 58,
					cacheable: true,
					optional: false,
					orphan: false,
					dependent: true,
					issuer: "/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/buffer/index.js",
					issuerName: "./node_modules/buffer/index.js",
					issuerPath: [
						{
							identifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
							name: "./src/index.ts",
							profile: {
								total: 0,
								resolving: 0,
								restoring: 0,
								building: 0,
								integration: 0,
								storing: 0,
								additionalResolving: 0,
								additionalIntegration: 0,
								factory: 0,
								dependencies: 0,
							},
							id: "./src/index.ts",
						},
						{
							identifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/utils/graphml.ts",
							name: "./src/utils/graphml.ts",
							profile: {
								total: 0,
								resolving: 0,
								restoring: 0,
								building: 0,
								integration: 0,
								storing: 0,
								additionalResolving: 0,
								additionalIntegration: 0,
								factory: 0,
								dependencies: 0,
							},
							id: "./src/utils/graphml.ts",
						},
						{
							identifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/xml-js/lib/index.js",
							name: "./node_modules/xml-js/lib/index.js",
							profile: {
								total: 0,
								resolving: 0,
								restoring: 0,
								building: 0,
								integration: 0,
								storing: 0,
								additionalResolving: 0,
								additionalIntegration: 0,
								factory: 0,
								dependencies: 0,
							},
							id: "./node_modules/xml-js/lib/index.js",
						},
						{
							identifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/xml-js/lib/json2xml.js",
							name: "./node_modules/xml-js/lib/json2xml.js",
							profile: {
								total: 0,
								resolving: 0,
								restoring: 0,
								building: 0,
								integration: 0,
								storing: 0,
								additionalResolving: 0,
								additionalIntegration: 0,
								factory: 0,
								dependencies: 0,
							},
							id: "./node_modules/xml-js/lib/json2xml.js",
						},
						{
							identifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/buffer/index.js",
							name: "./node_modules/buffer/index.js",
							profile: {
								total: 0,
								resolving: 0,
								restoring: 0,
								building: 0,
								integration: 0,
								storing: 0,
								additionalResolving: 4,
								additionalIntegration: 0,
								factory: 0,
								dependencies: 4,
							},
							id: "./node_modules/buffer/index.js",
						},
					],
					failed: false,
					errors: 0,
					warnings: 0,
					profile: {
						total: 74,
						resolving: 69,
						restoring: 0,
						building: 5,
						integration: 0,
						storing: 0,
						additionalResolving: 0,
						additionalIntegration: 0,
						factory: 69,
						dependencies: 0,
					},
					id: "./node_modules/base64-js/index.js",
					issuerId: "./node_modules/buffer/index.js",
					chunks: ["main"],
					assets: [],
					reasons: [
						{
							moduleIdentifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/buffer/index.js",
							module: "./node_modules/buffer/index.js",
							moduleName: "./node_modules/buffer/index.js",
							resolvedModuleIdentifier:
								"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/buffer/index.js",
							resolvedModule: "./node_modules/buffer/index.js",
							type: "cjs require",
							active: true,
							explanation: "",
							userRequest: "base64-js",
							loc: "11:15-35",
							moduleId: "./node_modules/buffer/index.js",
							resolvedModuleId: "./node_modules/buffer/index.js",
						},
					],
					usedExports: null,
					providedExports: [
						"byteLength",
						"fromByteArray",
						"toByteArray",
					],
					optimizationBailout: [],
					depth: 5,
				},
			],
			origins: [
				{
					module: "",
					moduleIdentifier: "",
					moduleName: "",
					loc: "main",
					request: "./src/index.ts",
				},
			],
		},
	],
	modules: [
		{
			type: "module",
			moduleType: "javascript/auto",
			layer: null,
			size: 4899,
			sizes: { javascript: 4899 },
			built: true,
			codeGenerated: true,
			buildTimeExecuted: false,
			cached: false,
			identifier:
				"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
			name: "./src/index.ts",
			nameForCondition:
				"/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
			index: 0,
			preOrderIndex: 0,
			index2: 97,
			postOrderIndex: 97,
			cacheable: true,
			optional: false,
			orphan: false,
			issuer: null,
			issuerName: null,
			issuerPath: null,
			failed: false,
			errors: 0,
			warnings: 0,
			profile: {
				total: 0,
				resolving: 0,
				restoring: 0,
				building: 0,
				integration: 0,
				storing: 0,
				additionalResolving: 0,
				additionalIntegration: 0,
				factory: 0,
				dependencies: 0,
			},
			id: "./src/index.ts",
			issuerId: null,
			chunks: ["main"],
			assets: [],
			reasons: [
				{
					moduleIdentifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
					module: "./src/index.ts",
					moduleName: "./src/index.ts",
					resolvedModuleIdentifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
					resolvedModule: "./src/index.ts",
					type: "cjs self exports reference",
					active: true,
					explanation: "",
					userRequest: null,
					loc: "2:16-20",
					moduleId: "./src/index.ts",
					resolvedModuleId: "./src/index.ts",
				},
				{
					moduleIdentifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
					module: "./src/index.ts",
					moduleName: "./src/index.ts",
					resolvedModuleIdentifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
					resolvedModule: "./src/index.ts",
					type: "cjs self exports reference",
					active: true,
					explanation: "",
					userRequest: null,
					loc: "2:24-37",
					moduleId: "./src/index.ts",
					resolvedModuleId: "./src/index.ts",
				},
				{
					moduleIdentifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
					module: "./src/index.ts",
					moduleName: "./src/index.ts",
					resolvedModuleIdentifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
					resolvedModule: "./src/index.ts",
					type: "cjs self exports reference",
					active: true,
					explanation: "",
					userRequest: null,
					loc: "13:14-18",
					moduleId: "./src/index.ts",
					resolvedModuleId: "./src/index.ts",
				},
				{
					moduleIdentifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
					module: "./src/index.ts",
					moduleName: "./src/index.ts",
					resolvedModuleIdentifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
					resolvedModule: "./src/index.ts",
					type: "cjs self exports reference",
					active: true,
					explanation: "",
					userRequest: null,
					loc: "13:22-33",
					moduleId: "./src/index.ts",
					resolvedModuleId: "./src/index.ts",
				},
				{
					moduleIdentifier: null,
					module: null,
					moduleName: null,
					resolvedModuleIdentifier: null,
					resolvedModule: null,
					type: "entry",
					active: true,
					explanation: "",
					userRequest: "./src/index.ts",
					loc: "main",
					moduleId: null,
					resolvedModuleId: null,
				},
			],
			usedExports: null,
			providedExports: null,
			optimizationBailout: [
				"CommonJS bailout: this is used directly at 2:16-20",
				"CommonJS bailout: this is used directly at 13:14-18",
			],
			depth: 0,
		},
		{
			type: "module",
			moduleType: "javascript/auto",
			layer: null,
			size: 3418,
			sizes: { javascript: 3418 },
			built: true,
			codeGenerated: true,
			buildTimeExecuted: false,
			cached: false,
			identifier:
				"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/webpack-stats/webpackStats.ts",
			name: "./src/webpack-stats/webpackStats.ts",
			nameForCondition:
				"/mnt/disk273/doc/coding/webpack-dep-graph/src/webpack-stats/webpackStats.ts",
			index: 1,
			preOrderIndex: 1,
			index2: 23,
			postOrderIndex: 23,
			cacheable: true,
			optional: false,
			orphan: false,
			issuer: "/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
			issuerName: "./src/index.ts",
			issuerPath: [
				{
					identifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
					name: "./src/index.ts",
					profile: {
						total: 0,
						resolving: 0,
						restoring: 0,
						building: 0,
						integration: 0,
						storing: 0,
						additionalResolving: 0,
						additionalIntegration: 0,
						factory: 0,
						dependencies: 0,
					},
					id: "./src/index.ts",
				},
			],
			failed: false,
			errors: 0,
			warnings: 0,
			profile: {
				total: 251,
				resolving: 9,
				restoring: 0,
				building: 242,
				integration: 0,
				storing: 0,
				additionalResolving: 0,
				additionalIntegration: 0,
				factory: 9,
				dependencies: 0,
			},
			id: "./src/webpack-stats/webpackStats.ts",
			issuerId: "./src/index.ts",
			chunks: ["main"],
			assets: [],
			reasons: [
				{
					moduleIdentifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
					module: "./src/index.ts",
					moduleName: "./src/index.ts",
					resolvedModuleIdentifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
					resolvedModule: "./src/index.ts",
					type: "cjs require",
					active: true,
					explanation: "",
					userRequest: "./webpack-stats/webpackStats",
					loc: "30:21-60",
					moduleId: "./src/index.ts",
					resolvedModuleId: "./src/index.ts",
				},
			],
			usedExports: null,
			providedExports: ["WebpackStatsParser", "__esModule"],
			optimizationBailout: [],
			depth: 1,
		},
		{
			type: "module",
			moduleType: "javascript/auto",
			layer: null,
			size: 3837,
			sizes: { javascript: 3837 },
			built: true,
			codeGenerated: true,
			buildTimeExecuted: false,
			cached: false,
			identifier:
				"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/deps.config.ts",
			name: "./deps.config.ts",
			nameForCondition:
				"/mnt/disk273/doc/coding/webpack-dep-graph/deps.config.ts",
			index: 2,
			preOrderIndex: 2,
			index2: 0,
			postOrderIndex: 0,
			cacheable: true,
			optional: false,
			orphan: false,
			issuer: "/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
			issuerName: "./src/index.ts",
			issuerPath: [
				{
					identifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
					name: "./src/index.ts",
					profile: {
						total: 0,
						resolving: 0,
						restoring: 0,
						building: 0,
						integration: 0,
						storing: 0,
						additionalResolving: 0,
						additionalIntegration: 0,
						factory: 0,
						dependencies: 0,
					},
					id: "./src/index.ts",
				},
			],
			failed: false,
			errors: 0,
			warnings: 0,
			profile: {
				total: 26,
				resolving: 5,
				restoring: 0,
				building: 21,
				integration: 0,
				storing: 0,
				additionalResolving: 1,
				additionalIntegration: 0,
				factory: 5,
				dependencies: 1,
			},
			id: "./deps.config.ts",
			issuerId: "./src/index.ts",
			chunks: ["main"],
			assets: [],
			reasons: [
				{
					moduleIdentifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
					module: "./src/index.ts",
					moduleName: "./src/index.ts",
					resolvedModuleIdentifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/index.ts",
					resolvedModule: "./src/index.ts",
					type: "cjs require",
					active: true,
					explanation: "",
					userRequest: "../deps.config",
					loc: "35:20-45",
					moduleId: "./src/index.ts",
					resolvedModuleId: "./src/index.ts",
				},
				{
					moduleIdentifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/utils/graphml.ts",
					module: "./src/utils/graphml.ts",
					moduleName: "./src/utils/graphml.ts",
					resolvedModuleIdentifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/utils/graphml.ts",
					resolvedModule: "./src/utils/graphml.ts",
					type: "cjs require",
					active: true,
					explanation: "",
					userRequest: "../../deps.config",
					loc: "55:20-48",
					moduleId: "./src/utils/graphml.ts",
					resolvedModuleId: "./src/utils/graphml.ts",
				},
				{
					moduleIdentifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/webpack-stats/dependenciesUUIDMap.ts",
					module: "./src/webpack-stats/dependenciesUUIDMap.ts",
					moduleName: "./src/webpack-stats/dependenciesUUIDMap.ts",
					resolvedModuleIdentifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/webpack-stats/dependenciesUUIDMap.ts",
					resolvedModule:
						"./src/webpack-stats/dependenciesUUIDMap.ts",
					type: "cjs require",
					active: true,
					explanation: "",
					userRequest: "../../deps.config",
					loc: "40:20-48",
					moduleId: "./src/webpack-stats/dependenciesUUIDMap.ts",
					resolvedModuleId:
						"./src/webpack-stats/dependenciesUUIDMap.ts",
				},
				{
					moduleIdentifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/webpack-stats/webpackStats.ts",
					module: "./src/webpack-stats/webpackStats.ts",
					moduleName: "./src/webpack-stats/webpackStats.ts",
					resolvedModuleIdentifier:
						"/mnt/disk273/doc/coding/webpack-dep-graph/node_modules/ts-loader/index.js!/mnt/disk273/doc/coding/webpack-dep-graph/src/webpack-stats/webpackStats.ts",
					resolvedModule: "./src/webpack-stats/webpackStats.ts",
					type: "cjs require",
					active: true,
					explanation: "",
					userRequest: "../../deps.config",
					loc: "4:20-48",
					moduleId: "./src/webpack-stats/webpackStats.ts",
					resolvedModuleId: "./src/webpack-stats/webpackStats.ts",
				},
			],
			usedExports: null,
			providedExports: ["__esModule", "depsConfig"],
			optimizationBailout: [],
			depth: 1,
		},
	],
	entrypoints: {
		main: {
			name: "main",
			chunks: ["main"],
			assets: [{ name: "bundle.js", size: 541985 }],
			filteredAssets: 0,
			assetsSize: 541985,
			auxiliaryAssets: [],
			filteredAuxiliaryAssets: 0,
			auxiliaryAssetsSize: 0,
			children: {},
			childAssets: {},
			isOverSizeLimit: false,
		},
	},
	namedChunkGroups: {
		main: {
			name: "main",
			chunks: ["main"],
			assets: [{ name: "bundle.js", size: 541985 }],
			filteredAssets: 0,
			assetsSize: 541985,
			auxiliaryAssets: [],
			filteredAuxiliaryAssets: 0,
			auxiliaryAssetsSize: 0,
			children: {},
			childAssets: {},
			isOverSizeLimit: false,
		},
	},
	errors: [],
	errorsCount: 0,
	warnings: [],
	warningsCount: 0,
	children: [],
}
